### ISSUE TITLE
Inbuilt wifi/Bluetooth can be used as receiver??

### ISSUE THREAD

**Issue by PravarHegde** [rtlopez/esp-fc#100]
I would like to use built-in wifi as transmitter and receiver instead of external transceiver. It would be light weight so can be used for Brushed nano drone.

**Comment by AutoPlantBali** [comment]
@PravarHegde The internal WiFi configuration has been used for BetaFlight Configurator connections via TCP/IP, you can check it in the CLI

**Comment by AutoPlantBali** [comment]
rx elrs ep1, ep2, pp only weighs 0.44 - 0.5 gr, is this still heavy enough?

**Comment by PravarHegde** [comment]
Yes correct.  But it's not cost effective. Esp8266 flight controller would be around 300₹ (3.6$) . Happymodel 2.4GHz ELRS nano series receiver cost around 1500₹ ( 18 $) and nrf24 module cost around 80₹ (1$ ) .  elrs model cost around  5 times of flight controller.  That's why . Using Nrf24 connection or built-in wifi as receiver would be cost effective 🤔

**Comment by AutoPlantBali** [comment]
@PravarHegde The weight of the receiver is inversely proportional to the price, if you want it cheap maybe you can make it yourself from Github:
https://github.com/RomanLut/hx_espnow_rc

**Comment by rtlopez** [comment]
Hi @PravarHegde, I was thinking about it too and so far I haven't found a radio system that would be able to work directly with the ESP32. Do you have any suggestion?

**Comment by rtlopez** [comment]
@PravarHegde Note that it is not betaflight, this is completely differrent firmware, only betaflight configurator can be used to configure it. I think it's time to start thinking about forking the configurator, because many people often think it's betaflight.

I don't think a smartphone will give any good user experience. Especially Wifi consumes a lot of processing power, that would negatively affect overral performance. Also wifi connection suffer a lot in range and realiability. nfr24 would be an option, as the 4in1 multiprotocol module would be able to handle that. But that would significantly complicate the PCB and firmware. In my opinion, it is best to stick to proven and battle-tested solutions. But I don't mind if there is anyone willing to build and implement it ;)

**Comment by AutoPlantBali** [comment]
> @rtlopez installing betaflight on esp32 was my dream since 2021. Thank you for quick response 🙂.
> 
> I think nrf24 would be able to directly work with esp32 . Few clean flight old version support nrf24 (spi connection) as a receiver.
> 
> In espcopter (nano drone project) they used esp8266+mpu9250 as flight controller and built-in wifi as receiver. Smartphone as transmitter.
> 
> nrf24 or built-in wifi for the transceiver would be best for nano drone

The espcopter is a different firmware, the controller on the smartphone uses remoteXY apps, the flight distance is short and unstable for some smartphones.

**Comment by Boak29** [comment]
> Okay but reciver weight would be heavy for Brushed tiny drones. So  it would be better if  we can use inbuilt wifi or it would be better if we can add nrf24 module as receiver (through spi)

You can use wifippm with esp12, if it still feels heavy use esp01
